import mongoose, { Schema } from "mongoose";

const tagSchema = new Schema(
    {
        name: {
            type: String,
        },
        color: {
            type: String, //generated by ai
        },
    }, { timestamps: true }
)

export const Tag = mongoose.model("Tag", tagSchema)